//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Туристическое_агенство
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ТурАгенствоEntities2 : DbContext
    {
        public ТурАгенствоEntities2()
            : base("name=ТурАгенствоEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Отели> Отели { get; set; }
        public virtual DbSet<Страны> Страны { get; set; }
        public virtual DbSet<Туры> Туры { get; set; }
        public virtual DbSet<ФотоТура> ФотоТура { get; set; }
        public virtual DbSet<ТипыТуров> ТипыТуров { get; set; }
    }
}
